name: Daily Telegram Digest

on:
  schedule:
    # 08:00 і 20:00 Київський час (UTC+3)
    - cron: '0 5 * * *'   # 08:00 Kyiv
    - cron: '0 17 * * *'  # 20:00 Kyiv
  workflow_dispatch:       # дозволяє запускати вручну

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python tg_agent.py
